"""Pydantic models for the tactical_agent_response table."""

from pydantic import BaseModel
from typing import Optional, List, Any
from uuid import UUID
from datetime import datetime


class TacticalAgentResponse(BaseModel):
    """
    A single tactical relocation recommendation record, enriched with the
    family name from evacuee_family_profiles for display in the frontend list.

    Fields
    ------
    id              : PK of the tactical_agent_response row.
    created_at      : When the tactical agent run finished.
    profile_uuid    : FK to evacuee_family_profiles.uuid.
    confidence      : Matching confidence label ('high' | 'medium' | 'low' | None).
    agent_output    : Full Markdown report generated by GPT-4o.
    radii_data      : List of hub zone dicts (hub_label, center_lat, center_lng,
                      radius_m, semantic_score, total_amenities, amenity_counts…)
                      stored as JSONB; used by the frontend to draw circles.
    family_name     : Denormalised from evacuee_family_profiles for list display.
    """

    id: UUID
    created_at: datetime
    profile_uuid: UUID
    confidence: Optional[str] = None
    agent_output: str
    radii_data: Optional[List[Any]] = None
    family_name: str
