"""Pydantic models for tactical response tables.

Shared shape for both family_tactical_responses and
multi_family_tactical_responses (the multi-family query aliases
multi_family_uuid → profile_uuid so the same model works).
"""

from pydantic import BaseModel
from typing import Optional, List, Any
from uuid import UUID
from datetime import datetime


class TacticalAgentResponse(BaseModel):
    """
    A single tactical relocation recommendation record, enriched with the
    family/group name for display in the frontend list.

    Fields
    ------
    id              : PK of the response row.
    created_at      : When the tactical agent run finished.
    profile_uuid    : FK to the profile table (family or multi-family).
    confidence      : Matching confidence label ('high' | 'medium' | 'low' | None).
    agent_output    : Full Markdown report generated by GPT-4o.
    radii_data      : List of hub zone dicts (hub_label, center_lat, center_lng,
                      radius_m, semantic_score, total_amenities, amenity_counts…)
                      stored as JSONB; used by the frontend to draw circles.
    family_name     : Denormalised from the profile table for list display.
    """

    id: UUID
    created_at: datetime
    profile_uuid: UUID
    confidence: Optional[str] = None
    agent_output: str
    radii_data: Optional[List[Any]] = None
    family_name: str
