-- PCA components per statistical area, ready for clustering.
-- One row per stat_2022; columns are principal components from different feature groups.
CREATE TABLE IF NOT EXISTS public.pca_ready_for_clustering (
    stat_2022 INTEGER PRIMARY KEY,

    PC_EDUCATION_1 DOUBLE PRECISION NOT NULL,
    PC_EDUCATION_2 DOUBLE PRECISION NOT NULL,

    PC_TOURISM_1 DOUBLE PRECISION NOT NULL,
    PC_TOURISM_2 DOUBLE PRECISION NOT NULL,
    PC_TOURISM_3 DOUBLE PRECISION NOT NULL,

    PC_FOOD_1 DOUBLE PRECISION NOT NULL,
    PC_FOOD_2 DOUBLE PRECISION NOT NULL,

    PC_COMMUNITY_1 DOUBLE PRECISION NOT NULL,

    PC_OSM_INFRA_1 DOUBLE PRECISION NOT NULL,
    PC_OSM_INFRA_2 DOUBLE PRECISION NOT NULL,
    PC_OSM_INFRA_3 DOUBLE PRECISION NOT NULL,

    PC_RELIGIOUS_1 DOUBLE PRECISION NOT NULL,
    PC_RELIGIOUS_2 DOUBLE PRECISION NOT NULL,

    imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pca_ready_stat_2022
    ON public.pca_ready_for_clustering (stat_2022);
